name: trading
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.2=py38hecd8cb5_1001
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2021.1.19=hecd8cb5_1
  - certifi=2020.12.5=py38hecd8cb5_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.21.0=py38h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.1=py38hecd8cb5_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libsodium=1.0.18=h1de35cc_0
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1j=h9ed2024_0
  - parso=0.8.1=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.0.1=py38hecd8cb5_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - python=3.8.8=h88f2d9e_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py38h23ab428_1
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py38hecd8cb5_0
  - six=1.15.0=py38hecd8cb5_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py38h9ed2024_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.3=hb1e8313_3
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.12.0
    - aniso8601==9.0.1
    - astunparse==1.6.3
    - attrs==20.3.0
    - autobahn==21.3.1
    - automat==20.2.0
    - cachetools==4.2.1
    - cffi==1.14.5
    - chardet==4.0.0
    - cheroot==8.5.2
    - click==8.0.3
    - colorama==0.4.4
    - constantly==15.1.0
    - cryptography==3.4.6
    - cycler==0.10.0
    - dateparser==1.0.0
    - flask==2.0.2
    - flask-restful==0.3.9
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.27.1
    - google-auth-oauthlib==0.4.3
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - hyperlink==21.0.0
    - idna==2.10
    - incremental==21.3.0
    - itsdangerous==2.0.1
    - jaraco-functools==3.3.0
    - jinja2==3.0.2
    - joblib==1.0.1
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - more-itertools==8.10.0
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.2.3
    - pandas-datareader==0.10.0
    - pathlib==1.0.1
    - pillow==8.1.2
    - protobuf==3.15.6
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyopenssl==20.0.1
    - pyparsing==2.4.7
    - python-binance==0.7.9
    - pytz==2021.1
    - pyyaml==5.4.1
    - regex==2020.11.13
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - seaborn==0.11.1
    - service-identity==18.1.0
    - sklearn==0.0
    - ta-lib==0.4.19
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - twisted==21.2.0
    - txaio==21.2.1
    - typing-extensions==3.7.4.3
    - tzlocal==2.1
    - ujson==4.0.2
    - unicorn-binance-websocket-api==1.34.2
    - unicorn-fy==0.11.0
    - urllib3==1.26.3
    - websocket-client==0.58.0
    - websockets==10.0
    - werkzeug==2.0.2
    - wrapt==1.12.1
    - zope-interface==5.2.0
